### ISSUE TITLE
Switch branch should load the code for the new branch

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#148]

**Comment by guillep** [comment]
I just "suffered" this bug. It is very annoying because not only the code is not loaded, but also the synchronization view does not realize at all that the loaded code does not match the one in the repository. I even reached a state where even "forgetting" the repository and recreating it did not work. 

To solve it I had to 
 - unload every single package I had loaded from that repository
 - remove the repository directory from the iceberg cache
 - load it again (and thus clone it)
 - reload everything

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. Now checkout branch will offer a checkout preview now before doing anything.
