### ISSUE TITLE
DNU IceMetacelloRepositoryAdapter>>#hasNoLoadConflict: 

### ISSUE THREAD

**Issue by noha** [pharo-vcs/iceberg#189]
I tried to load again a project that has been loaded with iceberg before. I used

`Metacello new
  baseline: 'Aster';
  repository: 'filetree://./repository';
  load`

and got the DNU

**Comment by estebanlm** [comment]
yes, and there are some other problems with non implemented methods (`flushForScriptGet`)
this other example shows the problem too:
```Smalltalk
Metacello new
    githubUser: 'DuneSt' project: 'MaterialDesignLite' commitish: 'master' path: 'src';
    baseline: 'MaterialDesignLite';
    onWarningLog;
    load.
```

**Comment by dalehenrich** [comment]
How can Iceberg be breaking Metacllo ... this is a bit disturbing ... I haven't seen any pull requests from you guys on the Metacello project and I don't see a public fork of Metacello, so what's up? When were you guys going to inform me of the changes to the Metacello API?

**Comment by noha** [comment]
I don't know anything about changes. But Iceberg uses adapters for repositories and such and those are lacking methods that metacello calls

**Comment by dalehenrich** [comment]
This is a change to the Metacello apit:

```
Metacello new
    githubUser: 'DuneSt' project: 'MaterialDesignLite' commitish: 'master' path: 'src';
    baseline: 'MaterialDesignLite';
    onWarningLog;
    load.
```

I've never heard of #githubUser:project:commitish:path: ... this is information that is supposed to be provided by the repository url ....  

I am always open to pull request for Metacello but if you guys are extending the basic api of Metacello I cannot be expected to maintain it ... at least have the courtesy to drop me an email ... I am going through a [major refactoring of Metacello right now](https://github.com/dalehenrich/metacello-work/tree/gs_port) and if you guys don't follow the standard practice of making timely pull requests there will be potential for big problems down the road when I release this new work...

**Comment by jecisc** [comment]
@dalehenrich I see it in metacello-work: https://github.com/dalehenrich/metacello-work/blob/master/repository/Metacello-Base.package/Metacello.class/instance/githubUser.project.commitish.path..st

**Comment by dalehenrich** [comment]
Oops! I [see that the code properly formats the repository url, so at least I implemented it properly:)(https://github.com/dalehenrich/metacello-work/blob/master/repository/Metacello-Base.package/Metacello.class/instance/githubUser.project.commitish.path..st#L7-L10) ... 

There are things going on below the surface that has caused this little *comment jag* ... hopefully what is below the surface will stay below the surface:)

**Comment by npasserini** [comment]
I think we should explain some stuff. 

First, Iceberg does not extends Metacello's API. I do not know where did that  #githubUser:project:commitish:path: come from.

Second, there is a public fork of your work, here: https://github.com/npasserini/filetree, which has only one significant proposal, which is to allow Iceberg to handle github URLs, as can be seen here:
https://github.com/npasserini/filetree/commit/be5a80092672824dd51c144f8f9756b295effe3b. The reason why @dalehenrich didn't receive a PR is because it is still work in progress, you will receive one not far from now. But before that I think that we should talk a little and decide which is the best way to do it.

Also my fork is outdated and I didn't have the time to synchronize everything against your last versions, which might also imply that I make changes in the way I interact with gitfiletree. I am planning a big refactor about that for the next version 0.4, that is why I decided to postpone these tasks until I get my hands into that refactor.

Finally, I do not think that Iceberg "breaks" Metacello. The two bugs reported here are caused by the Iceberg/Metacello integration. What I mean is that this kind of probles can only arise if you try to use Iceberg to handle your github:// urls in your BaselineOf:. 
If Iceberg is getting into Metacello's way, you can just disable Iceberg integration and you will have your old Metacello + github tarballs experience untouched.

**Comment by dalehenrich** [comment]
I'm sorry that I made those accusations ... I allowed myself to go into "reactionary mode" and I should have just walked away and taken a break ...

Despite what I said earlier ... I can see very clearly that Iceberg does not break Metacello ... 

I don't want Metacello to break iceberg either, so I don't think that disabling iceberg is the right way to go either ... 

I want to believe that all problems have a solution and I want to extend, expand or contract Metacello to work well with tools ... clearly I do not know in particular what  technical problems you are solving, but in the last month I have added support to Metacello for  a non-Monticello based package loading system (see [CypressReferenceImplementation](https://github.com/dalehenrich/CypressReferenceImplementation)) so I have an appreciation of some of the challenges for integrating alternate repository implementations and since I'm still working in this area now is a good time to talk...

So if you could spend some time and give me some pointers/examples of the types of technical problems you are having in integrating with Metacello, then perhaps we can come to a satisfactory solution together..

**Comment by guillep** [comment]
Should not be happenning anymore in latest version. Please reopen if necessary
