### ISSUE TITLE
Clarify ssh key in settings

### ISSUE THREAD

**Issue by Uko** [pharo-vcs/iceberg#259]
I don't know where this thing comes from, but when I was searching in setting, I got a popup: "enter the path to your public key". I think that it comes from Iceberg, as it asked for a user name afterwards and suggests "git".

The point is that I have many ssh keys for different services, and asking for "github ssh key" or even for "git ssh key" will both explain me what I need to provide and who is asking for that

**Comment by estebanlm** [comment]
in fact, this should be disabled for now: next version of iceberg will *not* have ssh support (you need to provide https credentials).

and before anyone complains: this is because of a limitation of current version of libgit2 (0.23). There are rumours of functionality working on 0.25, but we still need to do the migration, and test it.

**Comment by Uko** [comment]
@estebanlm when is the "release" coming? Because the doc says that you have to load master branch and it is ~200 commits behind the other ones

**Comment by estebanlm** [comment]
well... we are polishing the branch "multi-remotes", then we are going to merge it to "0.4-dev" and then we are going to merge it to "master".
So, let's say one week ?

**Comment by Uko** [comment]
cool! thanks!

**Comment by guillep** [comment]
Should not be happening anymore in latest version. Please reopen if necessary
