### ISSUE TITLE
Move iceberg to the root of world menu

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#401]
In Pharo 7 Iceberg will be main tool. So it makes sense to move it to the root of world menu like Monticello

**Comment by jecisc** [comment]
Iceberg is at the root of the WorldMenu but at a random place. (first or last depending on how the pragma are resolved).

In order to finish to correct this issue we need to wait for a fix for the Pharo issue: 
https://pharo.fogbugz.com/f/cases/20247/Refactor-the-MostUsedTools-of-the-world-menu-to-cut-dependencies-and-use-priorities

**Comment by jecisc** [comment]
This issue was integrated in build 47 of Pharo 7. We can now work on this one.
