### ISSUE TITLE
Do not clear comment when commit is finished

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#423]
In commit UI we input message. But when we press commit (or push) then text is cleared when commit is finished.

**Comment by estebanlm** [comment]
I don't know if like this: I think I prefer a "load older message" as in MC (anyway, in git, messages should be different :P)

**Comment by dionisiydk** [comment]
I thing It is not related to what you say.
Now when you press commit window is not closed but text view with message became empty.
In case of MC at the end of commit it shows "preview" of committed version which includes comment.

**Comment by estebanlm** [comment]
yes, in a different window. In iceberg case, sync window stays open because you may want to do other stuff (like pushing commits).
remove comment is right because we do not want same comment to come over and over each commit... but I agree a "load older commits" may be useful.

now... maybe what you actually are requesting is to show some feedback once commit is done. Which is different to not remove the commit input :)

**Comment by dionisiydk** [comment]
Summary of my wishes:
- preview of commit with message and hash
- close sync window after commit (I never used it)

**Comment by jecisc** [comment]
I proposed in other issue to add a setting for the auto close of the sync window.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. Commit window is autoclosed if there are no more changes to commit.
