### ISSUE TITLE
Mutliple repositories with same name are shown as the same

### ISSUE THREAD

**Issue by rajula96reddy** [pharo-vcs/iceberg#432]
If in case I have a repository 'A' by author 'B' and a repository forked from this 'C' by author 'D' and if I first load the repository 'A' it gets loaded without any error. And when I tried to load the repository 'C', it is added to the list, but the contents in this are from 'A' not of 'C'

**Comment by estebanlm** [comment]
I'm sorry, I do not understand this explanation.
In general if you have project A and forked project A' you do not add a different repository but a different remote (since forked or not, is same project), then you can switch branches and pull/push from different remotes.
Yes, project names are unique for iceberg and that will not change in the near future (also, how you think you will differentiate if you have two projects called 'A' ?)

**Comment by rajula96reddy** [comment]
I am extremely sorry. It`s my fault. Didn`t give it a proper thought. Thank you for the explanation.
