### ISSUE TITLE
Unclear how to load package from GUI

### ISSUE THREAD

**Issue by apblack** [pharo-vcs/iceberg#466]
It's not obvious how to load a project from Iceberg — or perhaps it's deliberately not possible (see #184).

I've used Iceberg to load a newer version of an already-loaded project, so I assumed that it would be possible to load a new project from github.  I have cloned the github repo locally, and see a line in the Iceberg repositories browser where, under "loaded version" it says "No package loaded", and figured that there ought to be a way to load it.  Couldn't find one.

Then I loaded the package using 
    Metacello new 
        baseline: 'package'; 
        repository: 'github://restOfTheUrl';
        load

and Iceberg still says "no package loaded", even though it _is_ now loaded.  _Cmd-R_ didn't change this.

No doubt that this is a pilot error on my part.  But the issue remains: it's unclear how to use Iceberg for the simplest use case.

**Comment by astares** [comment]
What do you mean?

The upper pane is for project repos, so you add a repo at the top (an existing local repo or by cloning
with a git ULR). The repo has packages (as seen on the seond tab in the lower pane). When you only add the repo the packages are not loaded.

But you can right click on a package to load it. 

If the project has a baseline you can also right click and load the baselines (default) and with that load several packages at once that make up the project.

**Comment by apblack** [comment]
What I mean is that it is not obvious that this is what I should do.  

Now that I have loaded the baseline configuration by hand, these things do indeed appear as you say — if I open a new instance of Iceberg.  (The old one just continues to say "package not loaded" even after a refresh — I think that this is a bug.)  I expect to be able to right-click on that "package not loaded" text and be offered the chance to load the package.   Perhaps something like 

      Load Baseline configuration   Cmd-L
      (To load other packages, 
      use the packages tab below)

**Comment by estebanlm** [comment]
I think this does not applies. 
iceberg is a VCS, not a project manager (so is comparable to git, monticello, etc., not to maven, npm, etc.)

For that, Pharo provides metacello and iceberg provides a "baseline plugin", that allows you to load a project using a present baseline (with right click).

now, a simple package (not a projecy) can be loaded in packages panel. 

what we can do is to add "load baselines" plugin options to the repository options ?

**Comment by ftl2014** [comment]
With all due respect to the communities effort on iceberg, but let's be perfectly clear about this:
I never cared much about github, let alone about its ghastly terminology and interface. But whether I like or not, the decision has been made to move things to do github - and I am affected by this decision, and so are other users.
Before the decision, there was a specific workflow to load packages, I had to learn once and it has worked just fine ever since. But now, I am struggling to install a package, with exactly the same issues describedby apblack, jecisc, dalehenrich. If you entirely commit to GitHub, you as a community, have the obligation to at least put a simple Facade over that Rubenesque machine that calls itself GitHub. 
And I really hate that issue being so dismissed blatantly - you made the choice to move to GitHub, I didn't, and I don't see why others should lose time because of that.

But the funny thing is, I have had a far easier time to compiling C GitHub projects than to "load" a GitHub project into Pharo.  Somebody has to take up that issue - and it should be those people that are already familiar with how things work. That is your responsibility.
