### ISSUE TITLE
Hanging commit operation

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#550]
Finally I found how to reproduce strange hang of progress bars during commit operation from sync view.

So it is always happens when sync window is expanded to full screen

**Comment by guillep** [comment]
Yes, actually, this happens when the progress bar and the updated window are overlapped. This looks like an issue coming from Glamour?

As soon as the progress bar tries to redraw, it will invalidate the window below itself and launch a new redraw, which will relaunch a progress bar redraw. Recursively.

Workaround for now, try not to overlap iceberg windows with the progress bars (top left).

**Comment by dionisiydk** [comment]
Interesting.
With next Spec based version we will see if it is only Glamour problem

**Comment by dionisiydk** [comment]
Ok I close it.

**Comment by dionisiydk** [comment]
You can close issue.
I will reopen it if it's still the case,



2018-04-13 11:01 GMT+02:00 Guillermo <notifications@github.com>:
