### ISSUE TITLE
Add possibility to see current commit in Repositories/Package view

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#750]
Currently, in the "Repositories" and "Packages" views of a project, it is possible to see on which branch we're located. 

Maybe we could add a way to also see the hash of the commit we are currently on and to be able to copy it to the clipboard if we click on it.

Does that make sense to anyone else?

**Comment by guillep** [comment]
Yeah, it happens to me a lot that I want to see the commit. I don't really know if it is necessary, I need it because I'm debugging and doing crazy stuff most of the time.

As a workaround you can go to the "Repository" view (top right button) and take the top commit. That's what you're looking for.

**Comment by jecisc** [comment]
I often need to copy a commit SHA when I comment or open an issue. 

So I think it's not something that rare.

(I know the workarounds but I opened the issue in order to improve Iceberg itself. For now, I just use GitKraken for that)

**Comment by tesonep** [comment]
![image](https://user-images.githubusercontent.com/355455/39532324-ede40168-4e2c-11e8-8fd6-ee5bd6bcd2b3.png)

I have added to the packages windows, to the repository maybe we can add it as an option in extra.

What do you think?

**Comment by jecisc** [comment]
And if we click on it it goes to the clipboard?

Looks great!

**Comment by tesonep** [comment]
Yes... of course, that was the easy part...
