### ISSUE TITLE
Pulling and pushing to a gitolite server asks password

### ISSUE THREAD

**Issue by guillep** [pharo-vcs/iceberg#999]
From discussion, we have to see how to reproduce it.

http://gitolite.com/gitolite/

@martinmcclure

**Comment by martinmcclure** [comment]
A test repository is at this URL:

gitolite3@mist-project.org:testing

Right now it contains only a readme.md file.

@guillep , I will need your RSA public key in order to give you access.

Note that you also cannot clone this from within Iceberg. However, if you have a local clone you can point Iceberg at the clone and it will work, but cannot pull or push.

**Comment by guillep** [comment]
Send you one by PM

**Comment by martinmcclure** [comment]
Public key pushed to the server; you should be able to pull and push to 

gitolite3@mist-project.org:testing

from the Git command line.

**Comment by guillep** [comment]
Ok, I've found two bugs related to this:

1. The gitolite server somehow seems to accept both plain text authentication AND ssh. Then, when Iceberg tries to authenticate, it was first giving precedence to plain text, and thus you were prompted for username/password. I've already a fix for this, that allows me to clone your repo using a url like `ssh://gitolite3@mist-project.org/testing.git`

2. Related to the previous point,`gitolite3@mist-project.org:testing` is not a valid git url for us. The thing is that we have to parse the url to know the name we are going to put to the repository.

I'll have a fix posted soon.
